export const products = [
  {
    _id: '1',
    product_name: 'Nike Air Force 1 07',
    product_images: [
      "/Images/productE1.webp",
      "/Images/productE2.webp",
      "/Images/productE3.webp",
      "/Images/productE4.webp"
    ],
    product_category:'men',
    price:'110',
    isNewProduct:true,
    isRelatedProduct:false,
    countInStock:2,
    numOfReviews:4,
    product_description:"The radiance lives on in the Nike Air Force 1 ’07, the b-ball OG that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.",
    product_details:[
      "Foam midsole",
      "Perforations on the toe",
      "Rubber sole",
      "Shown: White/White",
      "Style: CW2288-111"
    ]
  },
  {
    _id: '2',
    product_name: "Nike Blazer Mid '77 Vintage",
    product_images: [
      "/Images/productE5.webp",
      "/Images/productE6.webp",
      "/Images/productE7.webp",
      "/Images/productE8.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:true,
    price:'105',
    countInStock:2,
    numOfReviews:4,
    product_description:"In the ‘70s, Nike was the new shoe on the block. So new in fact, we were still breaking into the basketball scene and testing prototypes on the feet of our local team. Of course, the design improved over the years, but the name stuck. The Nike Blazer Mid ’77 Vintage—classic since the beginning.",
    product_details:[
      "Vintage treatment on the midsole provides an old-school look.",
      "Exposed foam on the tongue provides a throwback look.",
      "Autoclave construction fuses the outsole to the midsole for a streamlined look that echoes the ‘70s design",
      "Leather and synthetic upper keeps the classic look of the original while adding comfort and support",
      "Style: BQ6806-100"
    ]
  },
  {
    _id: '3',
    product_name: "Nike Dunk Hi Retro",
    product_images: [
      "/Images/productE9.webp",
      "/Images/productE10.webp",
      "/Images/productE11.webp",
      "/Images/productE12.webp"
    ],
    product_category:'men',
    isNewProduct:false,
    isRelatedProduct:true,
    price:'125',
    countInStock:2,
    numOfReviews:4,
    product_description:"Created for the hardwood but taken to the streets, the '80s b-ball icon returns with crisp leather and retro colors. The classic hoops design channels '80s vintage back onto the streets while the padded, high-top collar adds an old-school look rooted to comfort.",
    product_details:[
      "Shown: White/White/Picante Red/Picante Red.",
      "Perforations on toe.",
      "Foam insole",
      "Style: DV0828-100"
    ]
  },
  {
    _id: '4',
    product_name: "Nike Air Max 90",
    product_images: [
      "/Images/productE13.webp",
      "/Images/productE14.jpeg", 
      "/Images/productE15.webp",
      "/Images/productE16.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'130',
    countInStock:1,
    numOfReviews:5,
    product_description:"Lace up and feel the legacy. Produced at the intersection of art, music and culture, this champion running shoe helped define the ‘90s. Worn by presidents, revolutionized through collabs and celebrated through rare colorways, its striking visuals, Waffle outsole and exposed Air cushioning keep it alive and well.",
    product_details:[
      "Originally designed for performance running, visible Air cushioning puts the history of comfort beneath your feet.",
      "Waffle outsole delivers traction, durability and heritage style.",
      "Shown: Wolf Grey/Phantom/Black/Burgundy Crush.",
      "Style: DQ4071-004"
    ]
  },
  {
    _id: '5',
    product_name: "Nike Dunk High Retro SE",
    product_images: [
      "/Images/productE17.webp",
      "/Images/productE18.webp",
      "/Images/productE19.webp",
      "/Images/productE20.webp"
    ],
    product_category:'men',
    isNewProduct:false,
    isRelatedProduct:false,
    price:'125',
    countInStock:1,
    numOfReviews:5,
    product_description:"Fireside style and a whole lotta freshness—this joyful take on the Dunk High is the perfect match for rosy cheeks, the first floating snowflakes and your favorite winter beverage. Plaid accents bring the warm feels, while twill and corduroy-like fabrics add a sophisticated touch to the storied basketball look. Oh, and let's not forget the seasonally appropriate colors. Don't worry—even if you've been naughty, you're gonna look nice.",
    product_details:[
      "Leather, twill and corduroy-like fabrics add texture and durability.",
      "Plaid accents add a festive feel that's never out of style.",
      "Shown: Summit White/Summit White/Light Silver/Light Silver",
      "Rubber outsole with classic hoops pivot circle adds durable traction and heritage style.",
      "Style: DV0826-100"
    ]
  },
  {
    _id: '6',
    product_name: "Nike Air VaporMax Plus",
    product_images: [
      "/Images/productE21.webp",
      "/Images/productE22.webp",
      "/Images/productE23.webp",
      "/Images/productE24.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'210',
    countInStock:1,
    numOfReviews:5,
    product_description:"The Nike Air VaporMax Plus looks to the past to propel you into the future. Nodding to the ’98 original with its floating cage and padded upper, it adds VaporMax Air technology to ramp up the comfort and create a modern look.",
    product_details:[
      "Not intended for use as Personal Protective Equipment (PPE)",
      "Reflective elements.",
      "Heel pull tab.",
      "Shown: Rattan/Khaki/Black/White.",
      "Style: DX3720-200"
    ]
  },
  {
    _id: '7',
    product_name: "LeBron Witness 7",
    product_images: [
      "/Images/productE25.webp",
      "/Images/productE26.webp",
      "/Images/productE27.webp",
      "/Images/productE28.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:true,
    price:'105',
    countInStock:1,
    numOfReviews:5,
    product_description:"The longer LeBron’s legendary career continues, the more his game needs a design that doesn’t weigh him down, yet can still control all that sublime power. So, we’ve created our lightest LeBron model but with the kind of bankable support that can help you stay in front of your opponent with the game on the line. Full-length Max Air cushioning helps you take off and land confidently, while lightweight mesh blends with containment cables to help keep you locked in for 4 quarters or more.",
    product_details:[
      "Foam and mesh tongue",
      "Padded collar",
      "Shown: White/Black/Metallic Silver",
      "Style: DM1123-100"
    ]
  },
  {
    _id: '8',
    product_name: "Nike Air Max 270",
    product_images: [
      "/Images/productE29.webp",
      "/Images/productE30.webp",
      "/Images/productE31.webp",
      "/Images/productE32.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'160',
    countInStock:1,
    numOfReviews:5,
    product_description:"Legendary Air gets lifted. Our 1st lifestyle Air Max brings you style, comfort and 270 degrees of Air to showcase one of our greatest innovations yet. Add a lightweight, airy upper and low-cut collar and you've got the perfect kicks for everyday fun.",
    product_details:[
      "Foam in the midsole.",
      "Pull tab on heel.",
      "Shown: Midnight Navy/Bright Crimson/Black/White",
      "Style: FD0279-400"
    ]
  },
  {
    _id: '9',
    product_name: "Nike Air Max SYSTM",
    product_images: [
      "/Images/productE33.webp",
      "/Images/productE34.webp",
      "/Images/productE35.webp",
      "/Images/productE36.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'100',
    countInStock:1,
    numOfReviews:5,
    product_description:"Looks Max, feels Max. The Air Max SYSTM brings back everything you love about your favorite '80s vibes (without the parachute pants). Tried-and-true visible Nike Air cushioning pairs with a sleek, sport-inspired upper. It's Air Max delivering again.",
    product_details:[
      "Originally designed for performance running, Max Air cushioning delivers time-tested comfort.",
      "Inspired by all your favorite Air Max models from the '80s, you get heritage aesthetics with a modern feel.",
      "Mixed material upper delivers durability and breathability while a rubber outsole adds traction that lasts.",
      "Style: DM9537-102"
    ]
  },
  {
    _id: '10',
    product_name: "Nike Air Max 97",
    product_images: [
      "/Images/productE37.webp",
      "/Images/productE38.webp",
      "/Images/productE39.webp",
      "/Images/productE40.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'175',
    countInStock:1,
    numOfReviews:5,
    product_description:"Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead. Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colors and crisp details, it lets you ride in first-class comfort.",
    product_details:[
      "The foam sockliner feels soft and comfortable",
      "Pull tab",
      "Not intended for use as Personal Protective Equipment",
      "Shown: White/Black/Wolf Grey",
      "Style: 921826-101"
    ]
  },
  {
    _id: '11',
    product_name: "Nike Air Trainer SC High",
    product_images: [
      "/Images/productE41.webp",
      "/Images/productE42.webp",
      "/Images/productE43.webp",
      "/Images/productE44.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'150',
    countInStock:1,
    numOfReviews:5,
    product_description:"Channel your favorite multisport icons. Double TPU overlays help keep your foot feeling snug inside the shoe, allowing you to move from one activity to the next with confidence and comfort.",
    product_details:[
      "Not intended for use as Personal Protective Equipment (PPE)",
      "Shown: White/Black/University Blue/Metallic Silver",
      "Style: DQ7646-100"
    ]
  },
  {
    _id: '12',
    product_name: "Air Jordan 1 Mid",
    product_images: [
      "/Images/productE45.webp",
      "/Images/productE46.webp",
      "/Images/productE47.webp",
      "/Images/productE48.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'125',
    countInStock:1,
    numOfReviews:5,
    product_description:"Inspired by the original AJ1, the Air Jordan 1 Mid offers fans a chance to follow in MJ's footsteps. Fresh color trims the clean, classic materials, imbuing modernity into a classic design.",
    product_details:[
      "An Air-Sole unit provides lightweight cushioning.",
      "Real and synthetic leather in the upper offers durability and structure.",
      "A solid rubber outsole gives you traction on a variety of surfaces.",
      "Textile tongue feels soft and comfortable.",
      "Shown: White/White/White",
      "Style: 554724-136"
    ]
  },
  {
    _id: '13',
    product_name: "Nike Blazer Mid '77 Premium",
    product_images: [
      "/Images/productE49.webp",
      "/Images/productE50.webp",
      "/Images/productE51.webp",
      "/Images/productE52.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:true,
    price:'115',
    countInStock:1,
    numOfReviews:5,
    product_description:"Styled for the ‘70s. Loved in the ‘80s. Classic in the ‘90s. Ready for the future. The Nike Blazer Mid gets you ready for wintertime with a cozy collar that pairs perfectly with your favorite seasonal sweater.",
    product_details:[
      "Custom tongue label",
      "Mid-cut collar",
      "Shown: Sail/Midnight Navy/Gum Medium Brown/Sail",
      "Style: DQ7672-100"
    ]
  },
  {
    _id: '14',
    product_name: "Nike SB Nyjah 3 PRM",
    product_images: [
      "/Images/productE53.webp",
      "/Images/productE54.webp",
      "/Images/productE55.webp",
      "/Images/productE56.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'115',
    countInStock:1,
    numOfReviews:5,
    product_description:"Light. Effortless. On point. The Nyjah 3 delivers the next iteration of the tried-and-true skate shoe. Incredible Zoom Air cushioning pairs with a honeycombed outsole that's grippy and featherlight so you can skate like the best.",
    product_details:[
      "Rubber outsole provides traction and durability.",
      "Pull tabs offer easy on and off.",
      "Vulcanized construction fuses the outsole to the upper for a streamlined look and a low-to-the-ground ride.",
      "Shown: Summit White/Tour Yellow/Lucky Green/Black",
      "Style: DQ7672-100"
    ]
  },
  {
    _id: '15',
    product_name: "Nike Juniper Trail 2 Next Nature",
    product_images: [
      "/Images/productE57.webp",
      "/Images/productE58.jpeg",
      "/Images/productE59.webp",
      "/Images/productE60.webp"
    ],
    product_category:'men',
    isNewProduct:false,
    isRelatedProduct:true,
    price:'85',
    countInStock:1,
    numOfReviews:5,
    product_description:"Break away from the norm and dash up that tempting trail in the Nike Juniper Trail 2. Durable material on top and tough traction on the bottom give you a consistent, confident ride for those off-road runs calling your name. It's built for earthy terrain and unbeaten paths, with reliable traction that'll help keep you on course.",
    product_details:[
      "Foam midsole",
      "Pull loops",
      "Shown: Gorge Green/Deep Royal Blue/Coconut Milk/Yellow Strike",
      "Style: DM0822-301"
    ]
  },
  {
    _id: '16',
    product_name: "Nike Pegasus Trail 4 GORE-TEX",
    product_images: [
      "/Images/productE61.webp",
      "/Images/productE62.webp",
      "/Images/productE63.webp",
      "/Images/productE64.jpeg"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:true,
    price:'160',
    countInStock:1,
    numOfReviews:5,
    product_description:"The Nike Pegasus Trail 4 GORE-TEX is your running companion for those days when the weather turns. Its waterproof GORE-TEX layer helps keep your feet dry, and less rubber in the outsole creates a smooth transition from road to trail without breaking stride.",
    product_details:[
      "The inspirational message by the heel will vary between 'JUST DO IT' and 'JUST RUN IT' depending on the shoe",
      "Heel and tongue pull tabs",
      "Not intended for use as Personal Protective Equipment (PPE)",
      "Shown: Sanddrift/Obsidian/Mineral Teal/Racer Blue",
      "Style: DJ7926-100"
    ]
  },
  {
    _id: '17',
    product_name: "Zoom Freak 4 'Cookies and Cream'",
    product_images: [
      "/Images/productE65.webp",
      "/Images/productE66.webp",
      "/Images/productE67.webp",
      "/Images/productE68.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'117.97',
    countInStock:1,
    numOfReviews:5,
    product_description:"Giannis is an incessant storm of stamina and skill that keeps coming at opponents for 4 quarters or more. The forward-thinking design of his latest signature shoe helps propel you down the court in a lightweight fit that moves with you. It can handle quick changes in direction on both sides of the floor, giving you side-to-side stability and multidirectional traction as you Euro step to the hoop. The colors pay tribute to 1 of the Greek Freak’s favorite nighttime snacks.",
    product_details:[
      "This version is made for outdoor court use with its extra-durable rubber outsole.",
      "Cutouts in the foam under the toe and heel help reduce overall weight.",
      "Molded grooves in the rubber outsole allow the shoes to bend and flex.",
      "Shown: Black/Light Smoke Grey/University Blue/White",
      "Style: DJ6149-001"
    ]
  },
  {
    _id: '18',
    product_name: "Nike Air Zoom G.T. Cut 2",
    product_images: [
      "/Images/productE69.webp",
      "/Images/productE70.webp",
      "/Images/productE71.webp",
      "/Images/productE72.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:true,
    price:'170',
    countInStock:1,
    numOfReviews:5,
    product_description:"The Nike Air Zoom G.T. Cut 2 helps you stop on a dime and accelerate back into the open lane in a low-to-the-ground design that helps increase court contact while switching direction. Separate the players from the playmakers in a model that’s built on creating separation but supportive enough to help you play all day.",
    product_details:[
      "Lacing directly through the medial and lateral webbing loops adds forefoot support.",
      "Visible breathability in the lightweight upper provides a comfortable fit.",
      "Stiff clip around the heel helps lock your foot in over the cushioning.",
      "React foam in the insole adds responsive comfort.",
      "Molded tongue extends to the toe area and expands for comfort.",
      "Plush interior makes it ideal for players who want to feel quick without sacrificing comfort or control.",
      "Shown: Leche Blue/Ashen Slate/Green Glow/Green Shock",
      "Style: DJ6015-403"
    ]
  },
  {
    _id: '19',
    product_name: "Nike Cosmic Unity 2",
    product_images: [
      "/Images/productE73.webp",
      "/Images/productE74.webp",
      "/Images/productE75.webp",
      "/Images/productE76.jpeg"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:true,
    price:'160',
    countInStock:1,
    numOfReviews:5,
    product_description:"Celebrate the love and joy of the game with the Nike Cosmic Unity 2. Made with at least 20% recycled content by weight, it provides enhanced responsiveness and support. This shoe will help keep you fresh and secure without overloading it with extra ounces, so that you can focus on locking down the perimeter defensively or starting the fast break after a rebound.",
    product_details:[
      "New material in the upper balances stability and containment.",
      "A full-length Air Zoom Strobel with foam in the midsole provides the energy return you need to play extended minutes.",
      "Underfoot cushioning for all-game comfort.",
    ]
  },
  {
    _id: '20',
    product_name: "Air Jordan 1 Retro High OG",
    product_images: [
      "/Images/productE77.webp",
      "/Images/productE78.webp",
      "/Images/productE79.webp",
      "/Images/productE80.webp"
    ],
    product_category:'men',
    isNewProduct:true,
    isRelatedProduct:false,
    price:'180',
    countInStock:1,
    numOfReviews:5,
    product_description:"The Air Jordan 1 Retro High remakes the classic sneaker, giving you a fresh look with a familiar feel. Premium materials with new colors and textures give modern expression to an all-time favorite.",
    product_details:[
      "Wings logo stamped on collar",
      "Stitched-down Swoosh logo",
      "Genuine leather",
      "Rubber traction",
      "Foam sole",
      "Shown: Gorge Green/White/Metallic Silver",
      "Style: DZ5485-303"
    ]
  }
]



//WOMEN PRODUCTS
export const womenProducts = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/w1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/w2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/w3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/w4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/w5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/w6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/w7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/w8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/w9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/w10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    image: '/images/w11.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    image: '/images/w12.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/images/w13.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '14',
    image: '/images/w14.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '15',
    image: '/images/w15.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '16',
    image: '/images/w16.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '17',
    image: '/images/w17.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '18',
    image: '/images/w18.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '19',
    image: '/images/w19.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '20',
    image: '/images/w20.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

//XCLUSIVE PRODUCTS
export const WomenXclusive = [
  {
    _id: '1',
    name: 'Menns',
    image: '/Images/wx1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/Images/wx2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/Images/wx3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/Images/wx4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/Images/wx5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/Images/wx6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/Images/wx7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/Images/wx8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/Images/wx9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/Images/wx10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    image: '/Images/wx11.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    image: '/Images/wx12.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/Images/wx13.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '14',
    image: '/Images/wx14.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '15',
    image: '/Images/wx15.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '16',
    image: '/Images/wx16.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '17',
    image: '/Images/wx17.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '18',
    image: '/Images/wx18.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '19',
    image: '/Images/wx19.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '20',
    image: '/Images/wx20.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },

];
//NEW PRODUCTS
export const WnewProducts = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/n1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/n2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/n3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/n4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/n5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/n6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/n7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/n8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/n9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/n10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

//HARD DRIVE    
export const relatedProducts = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/hd1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/hd2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/hd3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/hd4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/hd5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/hd6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/hd7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/hd8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/hd9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/hd10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]



//MEN PRODUCTS
export const MenProducts = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/m1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/m2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/m3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/m4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/m5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/m6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/m7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/m8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/m9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/m10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    image: '/images/m11.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    image: '/images/m12.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/images/m13.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '14',
    image: '/images/m14.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '15',
    image: '/images/m15.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '16',
    image: '/images/m10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '17',
    image: '/images/m17.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '18',
    image: '/images/m18.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '19',
    image: '/images/m19.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '20',
    image: '/images/m20.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]
//MEN PRODUCTS
export const MenXclusive = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/mx1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/mx2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/mx3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/mx4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/mx5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/mx6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/mx7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/mx8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/mx9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/mx10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '1',
    image: '/images/mx11.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    image: '/images/mx12.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/images/mx13.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '14',
    image: '/images/mx14.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '15',
    image: '/images/mx15.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '16',
    image: '/images/mx16.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '17',
    image: '/images/mx17.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '18',
    image: '/images/mx18.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '19',
    image: '/images/mx19.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '20',
    image: '/images/mx20.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]


//MNEW PRODUCTS
export const MnewProducts = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/mn1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/mn2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/mn3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/mn4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/mn5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/mn6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/mn7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/mn8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/mn9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/mn10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];



//KIDS PRODUCTS
export const kidsProducts = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/k1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/k2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/k3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/k4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/k5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/k6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/k7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/k8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/k9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/k10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    image: '/images/k11.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    image: '/images/k12.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/images/k13.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '14',
    image: '/images/k14.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '15',
    image: '/images/k15.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '16',
    image: '/images/k16.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '17',
    image: '/images/k17.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '18',
    image: '/images/k18.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '19',
    image: '/images/k19.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '20',
    image: '/images/k20.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]

export const KnewProducts = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/kn1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/kn2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/kn3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/kn4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/kn5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/kn6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/kn7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/kn8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/kn9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/kn10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];


export const KidsXclusive = [
  {
    _id: '1',
    name: 'Menns',
    image: '/images/kx1.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sportees',
    image: '/images/kx2.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Sketchers',
    image: '/images/kx3.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sportees',
    image: '/images/kx4.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Papsae',
    image: '/images/kx5.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Fashion Sneakers',
    image: '/images/kx6.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '7',
    name: 'Canvas sneakers',
    image: '/images/kx7.svg',
    description:
      'Sneaker sport shoes',
    brand: 'vans',
    category: 'New',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Leather Boots',
    image: '/images/kx8.svg',
    description: 'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/images/kx9.svg',
    name: 'Merrell',
    description: 'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/images/kx10.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    image: '/images/kx11.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    image: '/images/kx12.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/images/kx13.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '14',
    image: '/images/kx14.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '15',
    image: '/images/kx15.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '16',
    image: '/images/kx16.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '17',
    image: '/images/kx17.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '18',
    image: '/images/kx18.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '19',
    image: '/images/kx19.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '20',
    image: '/images/kx20.svg',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]

//New products 

export const newproducts = [
  {
    _id: '1',
    image: '/Images/productE5.webp',
    name: 'Men Sneakers',
    description:
      'High top sneakers',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    image: '/Images/productsB.svg',
    name: 'Merrell',
    description:
      'Outdoor, fashion shoes',
    brand: 'Nike',
    category: 'New',
    price: 149.79,
    countInStock: 5,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Leather Boots',
    image: '/Images/productsC.svg',
    description:
      'Exotic jungle boots',
    brand: 'Addidas',
    category: 'New',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Menns',
    image: '/Images/productsT.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Fashion Sneakers',
    image: '/Images/productsE.svg',
    description:
      'lightweight sneakers',
    brand: 'puma',
    category: 'New',
    price: 349.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Papsae',
    image: '/Images/productsF.svg',
    description:
      'Mens fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Sportees',
    image: '/Images/productsG.svg',
    description:
      'Exotic joggers',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 5,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Sketchers',
    image: '/Images/productsH.svg',
    description:
      'Exotic sport shoes',
    brand: 'nike',
    category: 'New',
    price: 629.99,
    countInStock: 0,
    rating: 2.7,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Sportees',
    image: '/Images/productsI.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Menns',
    image: '/Images/productsJ.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Sportees',
    image: '/Images/productsK.svg',
    description:
      'Exotic joggers- yellow',
    brand: 'nike',
    category: 'New',
    price: 229.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Menns',
    image: '/Images/productsL.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Menns',
    image: '/Images/productsM.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Menns',
    image: '/Images/productsN.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '15',
    name: 'Menns',
    image: '/Images/productsO.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '16',
    name: 'Menns',
    image: '/Images/productsP.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '17',
    name: 'Menns',
    image: '/Images/productsQ.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '18',
    name: 'Menns',
    image: '/Images/productsR.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '19',
    name: 'Menns',
    image: '/Images/productsS.svg',
    description:
      'High top fashion shoes',
    brand: 'nike',
    category: 'New',
    price: 999.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  }
  // {
  //   _id: '20',
  //   name: 'Canvas sneakers',
  //   image: '/images/productsD.svg',
  //   description:
  //     'Sneaker sport shoes',
  //   brand: 'vans',
  //   category: 'New',
  //   price: 399.99,
  //   countInStock: 11,
  //   rating: 5,
  //   numReviews: 12,
  // }
]

export const featuredProducts = [
  {
    _id: '1',
    image: '/Images/featuredA.svg',
    name: 'Nike air jordan',
    description:
      'Nike Air Jordan 2021:Snipe In Grand Style',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    image: '/Images/featuredB.svg',
    name: 'Nike air max',
    description:
      'Nike Air Max 2021:Show Off In Grand Style',
    brand: 'Nike',
    category: 'New',
    price: 189.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '3',
    image: '/Images/featuredC.svg',
    name: 'Sportees Heelpeak AE0-2: 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 600.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '4',
    image: '/Images/featuredD.svg',
    name: 'Sportees GoRun B5-2: 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 600.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '5',
    image: '/Images/featuredE.svg',
    name: 'Sportees SnipeFeet G6-A: 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 600.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '6',
    image: '/Images/brandBG.svg',
    name: 'Lebron N-Walk Collection: 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 800.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '7',
    image: '/Images/featuredG.svg',
    name: 'Lebron N-Walk HL-43: 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 800.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '8',
    image: '/Images/featuredH.svg',
    name: 'Lebron N-Walk HL-43: 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 800.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '9',
    image: '/Images/featuredI.svg',
    name: 'Lebron N-Walk HL-43: 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 800.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '10',
    image: '/Images/featuredJ.svg',
    name: 'Nike Air Max 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 800.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    image: '/Images/featuredK.svg',
    name: 'Nike Air Max 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 800.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    image: '/Images/featuredL.svg',
    name: 'Nike Air Max 2021',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 800.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/Images/featuredM.svg',
    name: 'New Balance-Fresh Foam Roav',
    description:
      'Snipe in comfort: Get yours Now',
    brand: 'Sportess',
    category: 'New',
    price: 400.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/Images/menD.svg',
    name: 'New Balance-Fresh Foam Roav',
    description:
      'Sport sneakers for men',
    brand: 'Sportess',
    category: 'New',
    price: 400.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '13',
    image: '/Images/menE.svg',
    name: 'New Balance-Fresh Foam Roav',
    description:'GO RUN GO EASY',
    brand: 'Sportess',
    category: 'New',
    price: 400.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  }
]

export const productPageImages = [
  "/Images/productE1.webp",
  "/Images/productE2.webp",
  "/Images/productE3.webp",
  "/Images/productE4.webp"
]